logging:
  level:
    io.tries.rabbitmq: trace

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 5s
          multiplier: 1
        missing-queues-fatal: false

rabbit:
  brokers:
    - exchange: event.log
      routingKey: route.audit.log
      queue: queue.audit.log
      deadLetter: true

server:
  port: 9090
